import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  fullPage: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  centerPage: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 24,
  },
  card: {
    backgroundColor: '#ffffff',
    padding: 24,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#DDDDDD',
  },
  logoBox: {
    width: 72,
    height: 72,
    borderRadius: 20,
    backgroundColor: '#EAF2E9',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 20,
  },
  logoText: {
    fontWeight: '800',
    color: '#5C8B5A',
  },
  title: {
    fontSize: 26,
    fontWeight: '800',
    color: '#1A1A1A',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: '#888888',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
  },
  inputGroup: {
    marginBottom: 14,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#374151',
    marginBottom: 8,
  },
  input: {
    height: 48,
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 12,
    paddingHorizontal: 14,
    backgroundColor: '#ffffff',
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 12,
  },
  smallText: {
    fontSize: 13,
    color: '#888888',
  },
  linkText: {
    fontSize: 13,
    color: '#5C8B5A',
    fontWeight: '700',
  },
  primaryBtn: {
    height: 50,
    borderRadius: 14,
    backgroundColor: '#5C8B5A',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  primaryBtnText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 15,
  },
  outlineBtn: {
    height: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#5C8B5A',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  outlineBtnText: {
    color: '#5C8B5A',
    fontWeight: '800',
    fontSize: 15,
  },
  socialBtn: {
    height: 46,
    borderRadius: 14,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  socialBtnText: {
    color: '#1A1A1A',
    fontWeight: '700',
  },
  dividerText: {
    textAlign: 'center',
    color: '#9ca3af',
    marginVertical: 18,
  },
  bottomTextRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 16,
  },
  header: {
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#DDDDDD',
  },
  appTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1A1A1A',
  },
  mainArea: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 100,
  },
  attendanceCard: {
    backgroundColor: '#ffffff',
    padding: 18,
    borderRadius: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#DDDDDD',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  stampButton: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#5C8B5A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stampText: {
    color: '#ffffff',
    fontWeight: '900',
    fontSize: 12,
  },
  greenCard: {
    backgroundColor: '#EAF2E9',
    padding: 20,
    borderRadius: 20,
    marginBottom: 16,
  },
  cardBlock: {
    backgroundColor: '#ffffff',
    padding: 18,
    borderRadius: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#DDDDDD',
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1A1A1A',
    marginBottom: 6,
  },
  desc: {
    fontSize: 13,
    color: '#888888',
    lineHeight: 18,
  },
  creditText: {
    fontSize: 28,
    fontWeight: '900',
    color: '#5C8B5A',
    marginVertical: 8,
  },
  sectionHeader: {
    fontSize: 18,
    fontWeight: '900',
    color: '#1A1A1A',
    marginTop: 8,
    marginBottom: 12,
  },
  horizontalRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 18,
  },
  miniCard: {
    width: 140,
    padding: 14,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#DDDDDD',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  itemCard: {
    width: '47%',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: '#DDDDDD',
  },
  itemImage: {
    height: 100,
    borderRadius: 12,
    backgroundColor: '#DDDDDD',
    marginBottom: 10,
  },
  itemTitle: {
    fontWeight: '800',
    color: '#1A1A1A',
  },
  itemPrice: {
    color: '#5C8B5A',
    fontWeight: '800',
    marginTop: 4,
  },
  bottomNav: {
    height: 72,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#DDDDDD',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  navItem: {
    padding: 10,
  },
  navText: {
    color: '#9ca3af',
    fontWeight: '700',
  },
  navTextActive: {
    color: '#5C8B5A',
  },
  bgTitle: {
    fontSize: 30,
    fontWeight: '900',
    color: '#1A1A1A',
    marginBottom: 8,
  },
  progressCard: {
    backgroundColor: '#ffffff',
    padding: 18,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#DDDDDD',
    marginBottom: 16,
  },
  progressTrack: {
    height: 10,
    backgroundColor: '#DDDDDD',
    borderRadius: 10,
    overflow: 'hidden',
  },
  progressFill: {
    width: '50%',
    height: '100%',
    backgroundColor: '#5C8B5A',
  },
  missionItem: {
    backgroundColor: '#ffffff',
    padding: 18,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#DDDDDD',
    marginBottom: 12,
  },
  creditSmall: {
    color: '#5C8B5A',
    fontWeight: '900',
    marginTop: 8,
  },
  chatItem: {
    backgroundColor: '#ffffff',
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#DDDDDD',
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#d1d5db',
  },
  chatName: {
    fontWeight: '900',
    color: '#1A1A1A',
    marginBottom: 4,
  },
  headerRow: {
    height: 56,
    paddingHorizontal: 20,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#DDDDDD',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backText: {
    fontSize: 24,
    fontWeight: '900',
  },
  productMiniHeader: {
    backgroundColor: '#ffffff',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#DDDDDD',
  },
  itemImageSmall: {
    width: 54,
    height: 54,
    borderRadius: 12,
    backgroundColor: '#DDDDDD',
  },
  messageRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginBottom: 10,
  },
  messageRowSent: {
    justifyContent: 'flex-end',
  },
  messageBubble: {
    maxWidth: '75%',
    backgroundColor: '#ffffff',
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#DDDDDD',
  },
  messageBubbleSent: {
    backgroundColor: '#5C8B5A',
  },
  messageText: {
    color: '#1A1A1A',
  },
  sentText: {
    color: '#ffffff',
  },
  chatInputArea: {
    flexDirection: 'row',
    padding: 12,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#DDDDDD',
    gap: 8,
  },
  chatInput: {
    flex: 1,
    height: 44,
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 22,
    paddingHorizontal: 16,
  },
  sendBtn: {
    paddingHorizontal: 16,
    borderRadius: 22,
    backgroundColor: '#5C8B5A',
    justifyContent: 'center',
  },
  sendText: {
    color: '#ffffff',
    fontWeight: '800',
  },
  mapPage: {
    flex: 1,
    padding: 16,
  },
  searchInput: {
    height: 48,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#DDDDDD',
    marginBottom: 12,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  filterActive: {
    backgroundColor: '#5C8B5A',
    color: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    overflow: 'hidden',
    fontWeight: '800',
  },
  filter: {
    backgroundColor: '#ffffff',
    color: '#374151',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    overflow: 'hidden',
    fontWeight: '700',
  },
  fakeMap: {
    flex: 1,
    backgroundColor: '#EAF2E9',
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  fakeMapText: {
    fontSize: 22,
    fontWeight: '900',
    color: '#5C8B5A',
  },
  pin: {
    position: 'absolute',
    top: 80,
    left: 80,
    fontSize: 30,
  },
  profileCard: {
    backgroundColor: '#ffffff',
    padding: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#DDDDDD',
    alignItems: 'center',
    marginBottom: 16,
  },
  largeAvatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#d1d5db',
    marginBottom: 12,
  },
  addressBox: {
    alignSelf: 'stretch',
    backgroundColor: '#EAF2E9',
    padding: 16,
    borderRadius: 16,
    marginTop: 16,
  },
  statRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#DDDDDD',
    padding: 12,
    alignItems: 'center',
  },
  statIcon: {
    fontSize: 24,
  },
  statNum: {
    fontSize: 18,
    fontWeight: '900',
    marginVertical: 4,
  },
  badgeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  badge: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#ffffff',
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: 24,
    borderWidth: 1,
    borderColor: '#DDDDDD',
  },
  gallery: {
    height: 260,
    borderRadius: 24,
    backgroundColor: '#DDDDDD',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  galleryText: {
    fontSize: 18,
    fontWeight: '900',
    color: '#888888',
  },
  sellerCard: {
    backgroundColor: '#ffffff',
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#DDDDDD',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginVertical: 16,
  },
  tempText: {
    fontWeight: '900',
    color: '#5C8B5A',
  },
  fixedBottom: {
    height: 76,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#DDDDDD',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    gap: 12,
  },
  heartBtn: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: '#DDDDDD',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heartText: {
    fontSize: 26,
  },
  chatActionBtn: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    backgroundColor: '#5C8B5A',
    alignItems: 'center',
    justifyContent: 'center',
  },
alertConfirmButton: {
  paddingVertical: 12,
  borderRadius: 8,
  backgroundColor: '#5C8B5A',
  alignItems: 'center',
  width: '100%',
},
alertConfirmText: {
  color: '#FFFFFF',
  fontSize: 15,
  fontWeight: '600',
},
});