import {StyleSheet} from 'react-native';
import {colors} from './colors';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.grayBackground,
  },
  fullPage: {
    flex: 1,
    backgroundColor: colors.grayBackground,
  },
  centerPage: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 24,
  },
  card: {
    backgroundColor: colors.white,
    padding: 24,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  logoBox: {
    width: 72,
    height: 72,
    borderRadius: 20,
    backgroundColor: colors.chatGreen,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 20,
  },
  logoText: {
    fontWeight: '800',
    color: colors.primary,
  },
  title: {
    fontSize: 26,
    fontWeight: '800',
    color: colors.textPrimary,
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: colors.textMuted,
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
  },
  inputGroup: {
    marginBottom: 14,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textDark,
    marginBottom: 8,
  },
  input: {
    height: 48,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    backgroundColor: colors.inputBackground,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 12,
  },
  smallText: {
    fontSize: 13,
    color: colors.textMuted,
  },
  linkText: {
    fontSize: 13,
    color: colors.primary,
    fontWeight: '700',
  },
  primaryBtn: {
    height: 50,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  primaryBtnText: {
    color: colors.textLight,
    fontWeight: '800',
    fontSize: 15,
  },
  outlineBtn: {
    height: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  outlineBtnText: {
    color: colors.primary,
    fontWeight: '800',
    fontSize: 15,
  },
  socialBtn: {
    height: 46,
    borderRadius: 14,
    backgroundColor: colors.inputBackground,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  socialBtnText: {
    color: colors.textPrimary,
    fontWeight: '700',
  },
  dividerText: {
    textAlign: 'center',
    color: colors.textMuted,
    marginVertical: 18,
  },
  bottomTextRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 16,
  },
  header: {
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  appTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: colors.textPrimary,
  },
  mainArea: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 100,
  },
  attendanceCard: {
    backgroundColor: colors.white,
    padding: 18,
    borderRadius: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  stampButton: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stampText: {
    color: colors.textLight,
    fontWeight: '900',
    fontSize: 12,
  },
  greenCard: {
    backgroundColor: colors.greenBackground,
    padding: 20,
    borderRadius: 20,
    marginBottom: 16,
  },
  cardBlock: {
    backgroundColor: colors.white,
    padding: 18,
    borderRadius: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.textPrimary,
    marginBottom: 6,
  },
  desc: {
    fontSize: 13,
    color: colors.textMuted,
    lineHeight: 18,
  },
  creditText: {
    fontSize: 28,
    fontWeight: '900',
    color: colors.primary,
    marginVertical: 8,
  },
  sectionHeader: {
    fontSize: 18,
    fontWeight: '900',
    color: colors.textPrimary,
    marginTop: 8,
    marginBottom: 12,
  },
  horizontalRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 18,
  },
  miniCard: {
    width: 140,
    padding: 14,
    backgroundColor: colors.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  itemCard: {
    width: '47%',
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  itemImage: {
    height: 100,
    borderRadius: 12,
    backgroundColor: colors.inputBackground,
    marginBottom: 10,
  },
  itemTitle: {
    fontWeight: '800',
    color: colors.textPrimary,
  },
  itemPrice: {
    color: colors.primary,
    fontWeight: '800',
    marginTop: 4,
  },
  bottomNav: {
    height: 72,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  navItem: {
    padding: 10,
  },
  navText: {
    color: colors.textMuted,
    fontWeight: '700',
  },
  navTextActive: {
    color: colors.primary,
  },
  bgTitle: {
    fontSize: 30,
    fontWeight: '900',
    color: colors.textPrimary,
    marginBottom: 8,
  },
  progressCard: {
    backgroundColor: colors.white,
    padding: 18,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 16,
  },
  progressTrack: {
    height: 10,
    backgroundColor: colors.inputBackground,
    borderRadius: 10,
    overflow: 'hidden',
  },
  progressFill: {
    width: '50%',
    height: '100%',
    backgroundColor: colors.primary,
  },
  missionItem: {
    backgroundColor: colors.white,
    padding: 18,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 12,
  },
  creditSmall: {
    color: colors.primary,
    fontWeight: '900',
    marginTop: 8,
  },
  chatItem: {
    backgroundColor: colors.white,
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.inputBackground,
  },
  chatName: {
    fontWeight: '900',
    color: colors.textPrimary,
    marginBottom: 4,
  },
  headerRow: {
    height: 56,
    paddingHorizontal: 20,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  backText: {
    fontSize: 24,
    fontWeight: '900',
  },
  productMiniHeader: {
    backgroundColor: colors.white,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  itemImageSmall: {
    width: 54,
    height: 54,
    borderRadius: 12,
    backgroundColor: colors.inputBackground,
  },
  messageRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    marginBottom: 10,
  },
  messageRowSent: {
    justifyContent: 'flex-end',
  },
  messageBubble: {
    maxWidth: '75%',
    backgroundColor: colors.white,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  messageBubbleSent: {
    backgroundColor: colors.primary,
  },
  messageText: {
    color: colors.textPrimary,
  },
  sentText: {
    color: colors.white,
  },
  chatInputArea: {
    flexDirection: 'row',
    padding: 12,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: 8,
  },
  chatInput: {
    flex: 1,
    height: 44,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 22,
    paddingHorizontal: 16,
  },
  sendBtn: {
    paddingHorizontal: 16,
    borderRadius: 22,
    backgroundColor: colors.primary,
    justifyContent: 'center',
  },
  sendText: {
    color: colors.white,
    fontWeight: '800',
  },
  mapPage: {
    flex: 1,
    padding: 16,
  },
  searchInput: {
    height: 48,
    backgroundColor: colors.white,
    borderRadius: 16,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 12,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  filterActive: {
    backgroundColor: colors.primary,
    color: colors.white,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    overflow: 'hidden',
    fontWeight: '800',
  },
  filter: {
    backgroundColor: colors.white,
    color: colors.textPrimary,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    overflow: 'hidden',
    fontWeight: '700',
  },
  fakeMap: {
    flex: 1,
    backgroundColor: colors.inputBackground,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  fakeMapText: {
    fontSize: 22,
    fontWeight: '900',
    color: colors.primary,
  },
  pin: {
    position: 'absolute',
    top: 80,
    left: 80,
    fontSize: 30,
  },
  mapHeader: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: colors.white,
  },
  mapHeaderSub: {
    fontSize: 14,
    color: colors.textPrimary,
    fontWeight: '600',
    marginBottom: 4,
  },
  mapHeaderTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: colors.textPrimary,
    marginBottom: 12,
  },
  mapSearchContainer: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  mapSearchInput: {
    flex: 1,
    height: 48,
    backgroundColor: colors.white,
    borderRadius: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  mapSearchBtn: {
    width: 72,
    height: 48,
    backgroundColor: colors.primary,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapSearchBtnText: {
    color: colors.white,
    fontWeight: '700',
    fontSize: 15,
  },
  mapFilterRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  mapChip: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 25,
    backgroundColor: colors.inputBackground,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: 10,
  },
  mapChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  mapChipText: {
    fontSize: 14,
    color: colors.textPrimary,
    fontWeight: '600',
  },
  mapChipTextActive: {
    color: colors.white,
  },
  mapMain: {
    flex: 1,
    backgroundColor: colors.inputBackground,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapMainText: {
    fontSize: 40,
    fontWeight: '900',
    color: colors.textPrimary,
  },
  profileCard: {
    backgroundColor: colors.white,
    padding: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    marginBottom: 16,
  },
  largeAvatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: colors.inputBackground,
    marginBottom: 12,
  },
  addressBox: {
    alignSelf: 'stretch',
    backgroundColor: colors.inputBackground,
    padding: 16,
    borderRadius: 16,
    marginTop: 16,
  },
  statRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    alignItems: 'center',
  },
  statIcon: {
    fontSize: 24,
  },
  statNum: {
    fontSize: 18,
    fontWeight: '900',
    marginVertical: 4,
  },
  badgeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  badge: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: colors.white,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: 24,
    borderWidth: 1,
    borderColor: colors.border,
  },
  gallery: {
    height: 260,
    borderRadius: 24,
    backgroundColor: colors.inputBackground,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  galleryText: {
    fontSize: 18,
    fontWeight: '900',
    color: colors.textSecondary,
  },
  sellerCard: {
    backgroundColor: colors.white,
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginVertical: 16,
  },
  tempText: {
    fontWeight: '900',
    color: colors.primary,
  },
  fixedBottom: {
    height: 76,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    gap: 12,
  },
  heartBtn: {
    width: 52,
    height: 52,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heartText: {
    fontSize: 26,
  },
  chatActionBtn: {
    flex: 1,
    height: 52,
    borderRadius: 16,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
alertConfirmButton: {
  paddingVertical: 12,
  borderRadius: 8,
  backgroundColor: colors.primary,
  alignItems: 'center',
  width: '100%',
},
alertConfirmText: {
  color: colors.white,
  fontSize: 15,
  fontWeight: '600',
},
});