import {StyleSheet} from 'react-native';

export const homeStyles = StyleSheet.create({
  homeScroll: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  homeContainer: {
    padding: 20,
    paddingBottom: 100,
  },
  homeAttendanceCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#DDDDDD',
  },
  homeAttendanceTextBox: {
    flex: 1,
  },
  homeCardTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1A1A1A',
    marginBottom: 6,
  },
  homeCardDescription: {
    fontSize: 13,
    color: '#888888',
    lineHeight: 18,
  },
  homeStampCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#5C8B5A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  homeStampText: {
    color: '#ffffff',
    fontWeight: '900',
    fontSize: 12,
  },
  homeCreditCard: {
    backgroundColor: '#EAF2E9',
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
  },
  homeCreditTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  homeCreditRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginTop: 8,
  },
  homeCreditAmount: {
    fontSize: 28,
    fontWeight: '900',
    color: '#5C8B5A',
  },
  homeCreditUnit: {
    fontSize: 16,
    fontWeight: '700',
    color: '#5C8B5A',
    marginLeft: 4,
  },
  homeCreditButton: {
    backgroundColor: '#5C8B5A',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    marginTop: 12,
    alignSelf: 'flex-start',
  },
  homeCreditButtonText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 14,
  },
  homeRankingCard: {
    backgroundColor: '#ffffff',
    padding: 20,
    borderRadius: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#DDDDDD',
  },
  homeRankingList: {
    marginTop: 12,
  },
  homeRankingItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  homeRankingItemFirst: {
    backgroundColor: '#FEF9C3',
    borderRadius: 8,
    paddingHorizontal: 10,
    borderBottomWidth: 0,
  },
  homeRankingLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeRankingRank: {
    fontSize: 16,
    fontWeight: '900',
    color: '#1A1A1A',
    width: 24,
  },
  homeRankingDept: {
    fontSize: 14,
    color: '#374151',
    fontWeight: '700',
  },
  homeRankingCredit: {
    fontSize: 15,
    fontWeight: '800',
    color: '#5C8B5A',
  },
  homeRankingCreditUnit: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
  },
  homeBannerCard: {
    backgroundColor: '#F3F4F6',
    padding: 20,
    borderRadius: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: '#DDDDDD',
  },
  homeBannerDescription: {
    fontSize: 14,
    color: '#4B5563',
    marginTop: 4,
    marginBottom: 16,
  },
  homeBannerButton: {
    backgroundColor: '#1F2937',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  homeBannerButtonText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 14,
  },
  homeSectionTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#1A1A1A',
    marginBottom: 12,
  },
  homeMissionScrollContent: {
    paddingRight: 20,
    gap: 12,
  },
  homeMissionCard: {
    backgroundColor: '#ffffff',
    width: 240,
    padding: 16,
    borderRadius: 16,
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#DDDDDD',
  },
  homeMissionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1A1A1A',
    marginBottom: 6,
  },
  homeMissionDescription: {
    fontSize: 13,
    color: '#6B7280',
    marginBottom: 14,
    lineHeight: 18,
  },
  homeMissionBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  homeMissionReward: {
    fontSize: 14,
    fontWeight: '800',
    color: '#5C8B5A',
  },
  homeMissionButton: {
    backgroundColor: '#5C8B5A',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
  },
  homeMissionButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  homeSectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 12,
  },
  homeMoreText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#9CA3AF',
  },
  homeItemGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  homeItemCard: {
    width: '48%',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#DDDDDD',
    overflow: 'hidden',
  },
  homeItemImagePlaceholder: {
    height: 140,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  homeItemIcon: {
    fontSize: 48,
  },
  homeItemInfo: {
    padding: 12,
  },
  homeItemTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#1A1A1A',
    marginBottom: 4,
  },
  homeItemPrice: {
    fontSize: 14,
    fontWeight: '900',
    color: '#5C8B5A',
  },
  homeHeartButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  homeHeartIcon: {
    fontSize: 14,
    color: '#FF5252',
  },
});
